version: '3.8'
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal. jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local: latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    restart: always
    volumes:
    -  "./data: /home/dynamodblocal/data"
    working _dir: /home/dynamodblocal
    #basic healthcheck to indicate readiness
    healthcheck:
      test: ["CMD", "sh", "-c", "nc -z localhost 8000 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5

  dynamodb:
    image: "aaronshaf/dynamodb-admin"
    container_name: dynamodb-admin
    depends_on:
      - dynamodb-local
  restart: always
  ports:
    - "8001:8001"
  environment:
  -   DYNAMO_ENDPOINT=http://dynamodb-local:8000
  -   AWS_REGION=ap-southeast-1

  web:
    container hame: hangman-ui
    build:
      dockerfile: ./src/Dockerfile
      context: .
    ports:
    - "3000: 3000"
    volumes:
    - .:/app # Mounts the current directory into the container
  
  api:
    container_name: hangman-api
    build: # Tells Compose to build an image using the Dockerfile in the api directory
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./api:/app/api
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
    depends_on:
      - dynamodb-local
